//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRGDBEntities2 : DbContext
    {
        public PRGDBEntities2()
            : base("name=PRGDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OfferList> OfferList { get; set; }
        public virtual DbSet<RegistrationList> RegistrationList { get; set; }
        public virtual DbSet<ViewPageList> ViewPageList { get; set; }
        public virtual DbSet<ViewPageList1> ViewPageList1 { get; set; }
    }
}
