//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPageList
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Desripription { get; set; }
        public string ListOfFeatures { get; set; }
        public string DesriptionAfter { get; set; }
        public string URL { get; set; }
    }
}
